server:
  port: 8855

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: flyingDevil
    password: thakgayahunVro

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
